#https://github.com/marketplace/actions/automated-version-bump

name: 'Bump Version'

on:
  push:
    branches:
      - 'main'
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  bump-version:
    name: 'Bump Version'
    runs-on: ubuntu-latest
    # runs-on: [ self-hosted, tests ]

    steps:
      - name: 'Checkout source code'
        uses: 'actions/checkout@v3'
        with:
          token: ${{ secrets.TOKEN_WORKAROUND }}
          ref: ${{ github.ref }}

      - name: 'cat package.json'
        run: cat ./package.json

      - name: 'Automated Version Bump'
        id: version-bump
        uses: 'phips28/gh-action-bump-version@master'
        with:
          tag-prefix: 'v'
          commit-message: 'CI: bumps version to {{version}} [skip ci]'
        env:
          # TOKEN_WORKAROUND is a personal token, set at organization level, to bypass branch protection rules
          # this must be also set in actions/checkout@v3 action: https://github.com/phips28/gh-action-bump-version/issues/62
          GITHUB_TOKEN: ${{ secrets.TOKEN_WORKAROUND }}

      - name: 'cat package.json'
        run: cat ./package.json
        
      - name: 'Output Step'
        env:
          NEW_TAG: ${{ steps.version-bump.outputs.newTag }}
        run: echo "new tag $NEW_TAG"
